table ResumoDiario
	lineageTag: 39bde1dd-5a47-4d5d-a4cf-6af93e66212e

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: cf1a09dc-6221-4bdc-86a6-3200d415e4e9
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column chamados_conhecidos
		dataType: int64
		formatString: 0
		lineageTag: 19017ab7-1edf-4b69-a1f2-f9c93a5624fd
		summarizeBy: sum
		sourceColumn: chamados_conhecidos

		annotation SummarizationSetBy = Automatic

	column fila_todos
		dataType: int64
		formatString: 0
		lineageTag: 41f9111b-6150-45ec-94da-13481db11899
		summarizeBy: sum
		sourceColumn: fila_todos

		annotation SummarizationSetBy = Automatic

	column fila_sem_sinalizados
		dataType: int64
		formatString: 0
		lineageTag: 8e6c46e1-c989-4a19-9106-2e05b2437036
		summarizeBy: sum
		sourceColumn: fila_sem_sinalizados

		annotation SummarizationSetBy = Automatic

	column desconhecidos_todos
		dataType: int64
		formatString: 0
		lineageTag: 7e52f99e-7811-4d62-9657-1940fcb0f309
		summarizeBy: sum
		sourceColumn: desconhecidos_todos

		annotation SummarizationSetBy = Automatic

	column desconhecidos_sem_sinalizados
		dataType: int64
		formatString: 0
		lineageTag: 4a0a361a-2a1a-4a38-8e37-73fc07e38a91
		summarizeBy: sum
		sourceColumn: desconhecidos_sem_sinalizados

		annotation SummarizationSetBy = Automatic

	partition ResumoDiario = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "ResumoDiario.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Nulos = Table.ReplaceValue(Cabecalhos, "", null, Replacer.ReplaceValue, Table.ColumnNames(Cabecalhos)),
				    Tipos = Table.TransformColumnTypes(Nulos, {
				        {"data", type date},
				        {"chamados_conhecidos", Int64.Type},
				        {"fila_todos", Int64.Type},
				        {"fila_sem_sinalizados", Int64.Type},
				        {"desconhecidos_todos", Int64.Type},
				        {"desconhecidos_sem_sinalizados", Int64.Type}
				    }, "en-US")
				in
				    Tipos

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

